# name: Prettier

# on: 
#   pull_request:

# jobs:
#   prettier:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#         with:
#           # Make sure the actual branch is checked out when running on pull requests
#           ref: ${{ github.head_ref }}
#           # This is important to fetch the changes to the previous commit
#           fetch-depth: 0

#       - name: Prettify code
#         uses: creyD/prettier_action@v4.3
#         with:
#           # This part is also where you can pass other options, for example:
#           prettier_options: --check **/*.{js,md}
#           only_changed: False

name: Prettier

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust the Node.js version as per your project requirements

      - name: Install Prettier
        run: npm install --save-dev prettier

      - name: Check Code Formatting
        run: npx prettier --check "**/*.{js,ts,tsx,json}"
